config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'home' => 'pages#home'
  get 'new' => 'concerts#new'
  get 'show' => 'concerts#show'
  get 'edit' => 'concerts#edit'

  get 'genres/new' => 'genres#new'
  get 'artistes/new' => 'artistes#new'
  get 'seances/new' => 'seances#new'
  get 'places/new' => 'places#new'
  get 'typesplaces/new' => 'typesplaces#new'
  
  get 'concerts(.:format)' => 'concerts#index'
  get 'concerts/:id(.:format)' => 'concerts#show'
  get 'concerts/:id(.:format)/edit' => 'concerts#edit'
  get 'concerts/:id(.:format)/delete' => 'concerts#destroy'

  get 'genres(.:format)' => 'genres#index'
  get 'genres/:id(.:format)' => 'genres#show'
  get 'genres/:id(.:format)/edit' => 'genres#edit'
  get 'genres/:id(.:format)/delete' => 'genres#destroy'
  
  get 'artistes(.:format)' => 'artistes#index'
  get 'artistes/:id(.:format)' => 'artistes#show'
  get 'artistes/:id(.:format)/edit' => 'artistes#edit'
  get 'artistes/:id(.:format)/delete' => 'artistes#destroy'
  
  get 'seances(.:format)' => 'seances#index'
  get 'seances/:id(.:format)' => 'seances#show'
  get 'seances/:id(.:format)/edit' => 'seances#edit'
  get 'seances/:id(.:format)/delete' => 'seances#destroy'
  
  get 'typesplaces(.:format)' => 'typesplaces#index'
  get 'typesplaces/:id(.:format)' => 'typesplaces#show'
  get 'typesplaces/:id(.:format)/edit' => 'typesplaces#edit'
  get 'typesplaces/:id(.:format)/delete' => 'typesplaces#destroy'
  
  get 'places(.:format)' => 'places#index'
  get 'places/:id(.:format)' => 'places#show'
  get 'places/:id(.:format)/edit' => 'places#edit'
  get 'places/:id(.:format)/delete' => 'places#destroy'
  
  resources :concerts
  resources :genres
  resources :seances
  resources :artistes
  resources :types_de_places
  resources :places
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artiste.rb
class Artiste < ActiveRecord::Base
	has_many :seances
	
	def initialize(attributes = {})
		super
		self[:nom] = attributes[:nom]
	end
	
end

app/models/commentaire.rb
class Commentaire < ActiveRecord::Base
	belongs_to :compte, :concert 
	
end

app/models/concert.rb
class Concert < ActiveRecord::Base
	belongs_to :genre
	has_many :seances
	has_many :places
	has_many :commentaires
	
	
	def initialize(attributes = {})
		super
		self[:name] = attributes[:name]
	end
	
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :concerts
	#accepts_nested_attributes_for :concert
	
	
	
	def initialize(attributes = {})
		super
		self[:nom] = attributes[:nom]
	end

end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :types_de_place
	belongs_to :concert
	has_many :reservations
	
	def initialize(attributes = {})
		super
		self[:places] = attributes[:places]
		self[:prix] = attributes[:prix]
	end
	
	def ajout_place(nombre)
		self[:places] += nombre
	end
	
	def reservation_place(nombre)
		unless nombre > self[:places]
			self[:places] -= nombre
		end
	end
	
	def modifier_prix(prix)
		self[:prix] = prix
	end
	
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :place
	belongs_to :compte
end

app/models/seance.rb
class Seance < ActiveRecord::Base
	belongs_to :concert
	belongs_to :artiste
	
	def initialize(attributes = {})
		super
		self[:date] = attributes[:date]
	end
end

app/models/types_de_place.rb
class Typesplace < ApplicationRecord
	has_many :places
	
	def initialize(attributes = {})
		super
		self[:nom] = attributes[:nom]
	end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
	@genres = Genre.all
  end

  def new
	@genres = Genre.all
	@genre = Genre.new
	@concert = Concert.new
  end

  def create
	@genres = Genre.all
	@genre = Genre.new(genre_params)
	@genre.save
#	@genre.update(:concert_attributes => {:nom => "testValue"})
	if @genre.save
		redirect_to "http://localhost:3000/new"
	else
		redirect_to :back
	end
  end
  
  def edit
	@genre = Genre.find(params[:id])
  end
  
	def update
		@genre = Genre.find(params[:id])
		
		if @genre.update(genre_params)
			redirect_to @genre
		else 
			render 'edit'
		end
	end
  

  def show
	@genre = Genre.find(params[:id])
  end
  
	def destroy
		@genre = Genre.find(params[:id])
		@genre.destroy
		
		redirect_to concerts_path
	end
  
  	private
	def genre_params
		params.require(:genre).permit(:nom)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
	@places = Place.all
  end

  def new
	@places = Place.all
	@place = Place.new
	@concerts = Concert.all
	@typesplaces = Typesplace.all
  end

  def create
	@places = Place.all
	@concerts = Concert.all
	@typesplaces = Typesplace.all
	@place = Place.new(place_params)
	@place.save
	if @place.save
		redirect_to "http://localhost:3000/concerts"
	else
		redirect_to :back
	end
  end
  
  def edit
	@place = Place.find(params[:id])
  end
  
	def update
		@place = Place.find(params[:id])
		
		if @place.update(place_params)
			redirect_to @place
		else 
			render 'edit'
		end
	end
  

  def show
	@place = Place.find(params[:id])
  end
  
	def destroy
		@place = Place.find(params[:id])
		@place.destroy
		
		redirect_to concerts_path
	end
  
  	private
	def place_params
		params.require(:place).permit(:places, :prix, :typesplace_id, :concert_id)
	end

end

app/controllers/seances_controller.rb
class SeancesController < ApplicationController
  def index
	@seances = Seance.all
  end

  def new
	@seances = Seance.all
	@seance = Seance.new
	@concerts = Concert.all
	@artistes = Artiste.all
  end

  def create
	@seances = Seance.all
	@concerts = Concert.all
	@artistes = Artiste.all
	@seance = Seance.new(place_params)
	@seance.save
	if @seance.save
		redirect_to "http://localhost:3000/concerts"
	else
		redirect_to :back
	end
  end
  
  def edit
	@seance = Seance.find(params[:id])
  end
  
	def update
		@seance = Seance.find(params[:id])
		
		if @seance.update(place_params)
			redirect_to @seance
		else 
			render 'edit'
		end
	end

  def show
	@seance = Seance.find(params[:id])
	@seances = Seance.all
	@concerts = Concert.all
	@artistes = Artiste.all
  end
  
	def destroy
		@seance = Seance.find(params[:id])
		@seance.destroy
		
		redirect_to concerts_path
	end
  
  	private
	def place_params
		params.require(:seance).permit(:seances, :date, :concert_id, :artiste_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artistes_helper.rb
module ArtistesHelper
end

app/helpers/concert_helper.rb
module ConcertHelper
	def setup_concert(concert)
		concert.genre ||= Genre.new
		concert
	end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
	def setup_concert(concert)
		concert.genre ||= Genre.new
		concert
	end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/seances_helper.rb
module SeancesHelper
end

app/helpers/types_de_places_helper.rb
module TypesplacesHelper
end

app/views/genres/edit.html.erb
<h1> edit </h1>

<%= form_for :genre, url: genre_path(@genre), method: :patch do |c| %>
	
	<p>
		<%= c.label :nom %><br>
		<%= c.text_field :nom %>
	</p>
	<p>
		<%= c.submit %>
	</p>
	
<% end %>

<%= link_to 'Back', concerts_path %>

app/views/genres/index.html.erb
<h1> Genres </h1>
<ul>
  <% @genres.each do |genre| %>
    <li>
		<p><%= genre.inspect %></p>
		<p><%= genre.nom %></p>
	</li>
	<%= link_to "Show", genre_path(genre) %> <br/> 
		<%= link_to "Edit", edit_genre_path(genre) %><br/>
		<%= link_to "Destroy", genre_path(genre),
			method: :delete,
			data: {confirm: "Etes vous sûr ?"} %>
  <% end %>
</ul>
<%= link_to 'Liste concerts', concerts_path %>

app/views/genres/new.html.erb
<%= form_for :genre, url: genres_path do |f| %>
	
	<%= f.label :nom %>
	<%= f.text_field :nom %>

	<%= f.submit "Créer" %>
<% end %>

<%= link_to 'Liste des concerts', concerts_path %>

app/views/genres/show.html.erb
<h1> show </h1>

<p>
	<strong> ID: </strong>
	<%= @genre.id %>
</p>
<p>
	<strong> Nom: </strong>
	<%= @genre.nom %>
</p>

<%= link_to 'Liste concerts', concerts_path %>

app/views/places/edit.html.erb
<h1> Modification </h1>

<%= form_for :place, url: place_path(@place), method: :patch do |p| %>
	
	<p>
		<%= p.label :nombreplaces %><br>
		<%= p.text_field :places %>
	</p>
	<p>
		<%= p.label :prix %><br>
		<%= p.text_field :prix %>
	</p>
	<p>
		<%= p.submit %>
	</p>
	
<% end %>

<%= link_to 'Accueil', concerts_path %>

app/views/places/index.html.erb
<h1> Artistes </h1>
<ul>
  <% @places.each do |place| %>
    <li>
		<p><%= place.inspect %></p>
		<p><%= place.nom %></p>
	</li>
	<%= link_to "Show", place_path(place) %> <br/> 
		<%= link_to "Edit", edit_place_path(place) %><br/>
		<%= link_to "Destroy", place_path(place),
			method: :delete,
			data: {confirm: "Etes vous sûr ?"} %>
  <% end %>
</ul>
<%= link_to 'Accueil', concerts_path %>

app/views/places/new.html.erb
<h1>Nouvelle place</h1>

<%= form_for :place, url: places_path do |f| %>
	
	<%= f.label :nombredeplaces %>
	<%= f.text_field :places %><br/>
	<%= f.label :prix %>
	<%= f.text_field :prix %><br/>
	
	<%= f.label :type_de_place %>
	<%= f.select(:types_de_place_id) do %>
	<% 		@typesplaces.each do |t|	%>
	<%=  		content_tag(:option, t.nom, value: t.id) %>
	<% 		end
		end
	%><br/>
	
	<%= f.label :concert %>
	<%= f.select(:concert_id) do %>
	<% 		@concerts.each do |c|	%>
	<%=  		content_tag(:option, c.name, value: c.id) %>
	<% 		end
		end
	%><br/>

	<%= f.submit "Créer" %>
<% end %>

<%= link_to 'Accueil', concerts_path %>

app/views/places/show.html.erb
<h1>Places et tarifs</h1>
<p>
	<strong> Nombre de places : </strong>
	<%= @place.places %>
</p>
<p>
	<strong> Prix : </strong>
	<%= @place.prix %>
</p>

<%= link_to 'Accueil', concerts_path %>

app/views/seances/edit.html.erb
<h1> edit </h1>

<%= form_for :seance, url: seance_path(@seance), method: :patch do |c| %>
	
	<p>
		<%= c.label :date %><br>
		<%= c.text_field :date %>
	</p>
	<p>
		<%= c.submit %>
	</p>
	
<% end %>

<%= link_to 'Accueil', concerts_path %>

app/views/seances/index.html.erb
<h1> Seances </h1>
<ul>
  <% @seances.each do |seance| %>
    <li>
		<p><%= seance.inspect %></p>
		<p><%= seance.date %></p>
	</li>
	<%= link_to "Show", seance_path(seance) %> <br/> 
		<%= link_to "Edit", edit_seance_path(seance) %><br/>
		<%= link_to "Destroy", seance_path(seance),
			method: :delete,
			data: {confirm: "Etes vous sûr de vouloir supprimer ?"} %>
  <% end %>
</ul>
<%= link_to 'Liste concerts', concerts_path %>

app/views/seances/new.html.erb
<%= form_for :seance, url: seances_path do |f| %>
	
	Date :
	<%= f.date_select :date %><br/>
	
	Concert : 
	<%= f.select(:concert_id) do %>
	<% 		@concerts.each do |c|	%>
	<%=  		content_tag(:option, c.name, value: c.id) %>
	<% 		end
		end
	%><br/>
	Artiste :
	<%= f.select(:artiste_id) do %>
	<% 		@artistes.each do |t|	%>
	<%=  		content_tag(:option, t.nom, value: t.id) %>
	<% 		end
		end
	%><br/>

	<%= f.submit "Créer" %>
<% end %>

<%= link_to 'Accueil', concerts_path %>

app/views/seances/show.html.erb
<h1>Séances</h1>

	<% @concerts.each do |concert| %>
		<% 	if @seance.concert_id == concert.id %>
			<%= "Concert :	#{concert.name}" %> <br/>
		<% end %>
	<% end %>
	<% @artistes.each do |artiste| %>
		<% 	if @seance.artiste_id == artiste.id %>
			<%= "Artiste :	#{artiste.nom}" %> <br/>
		<% end %>
	<% end %>
	Date :
	<%= @seance.date %>

<%= link_to 'Accueil', concerts_path %>